path_config:
  output_dir: outputs/train/experiment
  checkpoint_path: null   # Optional
  pretrained_path: null   # Optional

dataset_config:
  train:
    type: ExampleDataset  
    dataset_params:   # Custom
      data_path: /path/to/train/data
      split: train
    dataloader_params: 
      batch_size: 64
      shuffle: true
      num_workers: 4

  val:    # Optional
    type: ExampleDataset
    dataset_params:
      data_path: /path/to/val/data
      split: val
    dataloader_params:
      batch_size: 1
      shuffle: false
      num_workers: 4

model_config:
  type: ExampleModel
  params:
    input_size: 1024
    output_size: 10
    dropout_rate: 0.5

train_config:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 20
  grad_clip: 1.0

  optimizer: 
    type: SGD
    params:
      lr: 0.001
      momentum: 0.9
      weight_decay: 0.0001

  scheduler:
    type: StepLR
    params:
      step_size: 5
      gamma: 0.1

  early_stopping:
    patience: 5
    min_delta: 0.01
    mode: min