model_config:
  input_size: 1024
  output_size: 10
  dropout_rate: 0.5

train_config:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 20
  optimizer: 
    type: Adam
    params:
      betas: [0.9, 0.999]
      eps: 1e-08
  scheduler:
    type: StepLR
    step_size: 5
    gamma: 0.1
  early_stopping:
    patience: 5
    min_delta: 0.01
    mode: min