path_config:  
  output_dir: outputs/train/mnist_experiment # Required or will be saved in the default
  checkpoint_path: null   # Optional
  pretrained_path: null   # Optional

dataset_config: 
  train:
    type: MnistDataset  # Required
    dataset_params:  # Custom and Optional
      root: "./data"
      split: true
      download: true
    dataloader_params: # Custom and Optional
      batch_size: 64
      shuffle: true
      num_workers: 4

  val:    # Optional
    type: MnistDataset  # Required
    dataset_params: # Custom and Optional
      root: "./data"
      split: false
      download: true
    dataloader_params: # Custom and Optional
      batch_size: 100
      shuffle: false
      num_workers: 4

model_config:
  type: MnistModel # Required
  # params: # Custom and Optional

train_config:
  num_epochs: 15  # Required
  grad_clip: 5.0 # Custom and Optional

  optimizer: # Required
    type: Adam # Required
    params: # Custom and Optional
      lr: 0.01
      weight_decay: 0.0001
      amsgrad: false

  scheduler: # Custom and Optional
    type: StepLR # Required
    params:
      step_size: 5
      gamma: 0.5   

  early_stopping: # Custom and Optional
    patience: 3
    min_delta: 0.001
    mode: max