path_config:  
  output_dir: outputs/train/mnist_experiment
  checkpoint_path: null   

dataset_config: 
  test:
    type: MnistDataset
    dataset_params:  
      root: "./data"
      split: true
      download: true
    dataloader_params: 
      batch_size: 64
      shuffle: false
      num_workers: 4

model_config:
  type: MnistModel
  # params: # Custom and Optional

test_config: